import Head from 'next/head';
import React from 'react';
import { Suspense } from 'react';
import Banner from '../components/Banner/Banner';
import Contact from '../components/Contact';
import Header from '../components/Header/Header';
import Home from '../components/Home';
import About from '../components/About';
import Recipe from '../components/Recipe';
import Footer from '../components/Footer';

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-poppins bg-back">
        <Suspense>
          <Header />
        </Suspense>
        <Suspense>
          <Banner />
        </Suspense>
        <Suspense>
          <Home />
        </Suspense>
        <Suspense>
          <About />
        </Suspense>
        <Suspense>
          <Recipe />
        </Suspense>
        <Suspense>
          <Contact />
        </Suspense>
        <Suspense>
          <Footer />
        </Suspense>
      </div>
    </>
  );
};

export default Index;
