import Head from "next/head";
import Image from "next/image";
import React from "react";
import Contact from "@/components/Contact";
import Header from "@/components/Header";
import Home from "@/components/Home";
import About from "@/components/About";
import NavIcon from "@/components/NavIcon";
import Recipe from "@/components/Recipe";
import Footer from "@/components/Footer";

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-poppins bg-back">
          <Header />
          <NavIcon />
          <Home />
          <About />
          <Recipe />
          <Contact />
          <Footer />
        </div>
    </>
  );
};

export default Index;
